version: 0.2
phases:
  install:
    commands:
      - npm i -g yarn@1.10.1
      - cd backend
      - yarn
      - cd ../frontend
      - yarn
      - cd ..
  build:
    commands:
      - cd frontend
      - yarn build
      - cd ../backend
      - yarn build
      - cd ..
  post_build:
    commands:
      - aws s3 sync ./frontend/dist s3://vmadarajtodolist.com

artifacts:
  files:
    - .yarnrc
    - .npmrc
    - dist/**/*
    - package.json
    - yarn.lock
    - todos.db

  base-directory: ./backend
